import {StyleSheet} from 'react-native';
import Theme from '../../utils/Theme';

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Theme.secondary,
    },
    heading: {
      backgroundColor: Theme.primary,
      color: Theme.secondary,
      padding: 15,
      textAlign: 'center',
      fontSize: 18,
      fontWeight: 'bold',
    },
    addBtn: {
      backgroundColor: Theme.primary,
      position: 'absolute',
      bottom: '5%',
      alignSelf: 'flex-end',
      right: '7%',
      width: 45,
      height: 45,
      borderRadius: 30,
      alignItems: 'center',
      justifyContent: 'center',
    },
    listView: {
      marginHorizontal: '3%',
      marginTop: '5%',
      flexGrow: 0,
      paddingHorizontal: 5,
      paddingVertical: 10,
      backgroundColor: Theme.secondary,
    },
    columnView: {
      marginVertical: '2%',
      padding: 8,
      backgroundColor: Theme.white,
      borderRadius: 5,
      borderWidth: 0.5,
      borderColor: Theme.gray,
      shadowColor: "#000",
  shadowOffset: {
      width: 0,
      height: 1,
  },
  shadowOpacity: 0.20,
  shadowRadius: 1.41,
  
  elevation: 2,
    },
    rowView: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: '1%',
      paddingBottom: 8,
      borderBottomWidth: 0.3,
      borderColor: Theme.gray,
    },
    label: {
      color: Theme.primary,
      fontSize: 16,
      fontWeight: 'bold',
      width: '80%',
    },
    innerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    edit: {
      marginRight: '2%',
    },
    desc: {
      marginVertical: '2%',
      color: Theme.black,
      fontSize: 14,
    },
    centeredView: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalView: {
      backgroundColor: Theme.white,
      borderRadius: 20,
      width: '95%',
      padding: 20,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    heading2: {
      color: Theme.black,
      alignSelf: 'center',
      textAlign: 'center',
      fontSize: 16,
      fontWeight: 'bold',
    },
    input: {
      borderWidth: 0.5,
      height: 40,
      marginBottom: '2%',
      marginTop: '5%',
      borderRadius: 3,
      paddingHorizontal: 5,
      borderColor: Theme.gray,
      color: Theme.black,
      fontSize: 15,
    },
    input2: {
      borderWidth: 0.5,
      borderColor: Theme.gray,
      borderRadius: 3,
      marginVertical: '2%',
      color: Theme.black,
      fontSize: 15,
      height: 150,
    },
    Btn: {
      backgroundColor: Theme.primary,
      alignSelf: 'center',
      marginVertical: '3%',
      paddingVertical: 8,
      paddingHorizontal: 15,
      borderRadius: 5,
    },
    btnText: {
      color: Theme.white,
      fontSize: 15,
    },
    errorMsg: {
      color: 'red',
      fontSize: 13,
      marginBottom: '2%',
    },
    text1: {
      color: Theme.primary,
      fontSize: 17,
      fontWeight: 'bold',
      alignSelf: 'center',
      marginHorizontal: '3%',
      marginTop: '10%',
    },
  });

export default styles